### ISSUE TITLE
Blog is published without styling

### ISSUE THREAD

**Issue by worldofgeese** [BlazorStatic/BlazorStaticMinimalBlog#6]
Hello!

I've forked the template, made changes to `first-post.md` and set GitHub Pages to publish from the `gh-pages` branch. However, my site is published without styling and it looks like the posts themselves are not navigable.

See https://worldofgeese.github.io:

![image](https://github.com/user-attachments/assets/1d56b223-1fd2-41ce-aebd-6b84741075f1)

Is there something I'm doing wrong in the publish pipeline? [Here's my repo](https://github.com/worldofgeese/worldofgeese.github.io).

**Comment by tesar-tech** [comment]
Hello,
thank you for pointing this out. 

This is a bug, that comes from this particular job in the build script: https://github.com/worldofgeese/worldofgeese.github.io/blob/96c6a6a707dc70274a229e1bab8648bc4604ea79/.github/workflows/publish-to-gh-pages.yml#L30

Remove that and you should be fine. 

What the job does is to change the base tag from `<base href="/" />` to `<base href="/yourRepoName" />`... Why?
Usually when you create a website it has the url like: `https://tesar-tech.github.io/BlazorStatic/` (where the repo name is `BlazorStatic`). For repositories, that matches `yourUserName.github.io` the page is just: `yourUserName.github.io` (nothing after .io/)... Build script isn't prepared for these "username" repositories. But the fix should be easy.


Let me know.

**Comment by tesar-tech** [comment]
the fix is done, can you merge the commit and test it on your side (instead of deleting the job like I advised earlier)?

**Comment by worldofgeese** [comment]
Your fix worked, thank you so much!
